# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    jobeet.admin.category:
        class: Ens\JobeetBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: jobeet, label: Catégories }
        arguments: [null, Ens\JobeetBundle\Entity\Category, JobeetBundle:CategoryAdmin ]
        
    jobeet.admin.job:
        class: Ens\JobeetBundle\Admin\JobAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, groupe: jobeet, label: Offres d'emploi }
        arguments: [ null, Ens\JobeetBundle\Entity\Job, JobeetBundle:JobAdmin ]


